version: "3"

services:
  backend:
    build: ./backend
    expose:
      - 3000
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/database.sqlite:/usr/src/app/database.sqlite

  frontend:
    build: ./frontend
    expose:
      - 80

  proxy:
    image: nginx:alpine
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
